#!/bin/bash

if [ "$1" = "--newday" ]; then
    currentDay="day$2"

    mkdir -p "./days/$currentDay"
    cp ./.template/__init__.py "./days/$currentDay/__init__.py"
    cp ./.template/day.py "./days/$currentDay/$currentDay.py"
    cp ./.template/test_day.py "./days/$currentDay/test_$currentDay.py"
    cp ./.template/input.txt "./days/$currentDay/input.txt"
elif [ "$1" = "--test" ]; then
  currentDay="day$2"
  python "./days/$currentDay/test_$currentDay.py"
else
    currentDay="day$1"
    python "./days/$currentDay/$currentDay.py"
fi
